services:
  - type: web
    name: crypto-arbitrage-bot
    env: node
    region: frankfurt
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm start
    nodeVersion: 20.x
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    autoDeploy: true
    healthCheckPath: /
